export const weDoAllSurgeons: string[] = [
	"RUBENS HUBER DA SILVA",
	"RAEL LUCAS MATIMOTO",
	"JOSE VICTOR MANIGLIA",
	"LUIZ SERGIO RAPOSO",
	"LUCIANO PEREIRA MANIGLIA",
	"ADRIANO GUIMARÃES REIS",
];

export const weOnlyDoDescriptionsSurgeons: string[] = [
	"CASSIANO RICARDO DANTAS MORETI",
	"CLAUDIA PEREIRA MANIGLIA",
];
