export const weDoAllSurgeons: string[] = [
	"ADRIANO GUIMARÃES REIS",
	"ANDRE LUIZ DEL ARCO",
	"FABIO DE AZEVEDO CAPARROZ",
	"JOSE VICTOR MANIGLIA",
	"LUCAS BORELLA PELOSI",
	"LUCIANO PEREIRA MANIGLIA",
	"LUIZ SERGIO RAPOSO",
	"MAURICIO PEREIRA MANIGLIA",
	"MAYRA COELHO BOCOLI",
	"RAEL LUCAS MATIMOTO",
	"RUBENS HUBER DA SILVA",
];

export const weOnlyDoDescriptionsSurgeons: string[] = [
	"CASSIANO RICARDO DANTAS MORETI",
	"CLAUDIA PEREIRA MANIGLIA",
];
